### ISSUE TITLE
External MQTT with internal Rhasspy instance

### ISSUE THREAD

**Issue by alve89** [JarvyJ/HomeIntent#548]
I'm not sure if I'm right but it seems that the following does not work:

```
rhasspy:
  disable_audio_at_base_station: true
  externally_managed: false
  mqtt_host: rpihass
  mqtt_port: 1883
  mqtt_username: homeintent
  mqtt_password: mysecret
  shared_satellite_config:
    mqtt_host: rpihass
    mqtt_port: 1883
    mqtt_username: homeintent
    mqtt_password: mysecret
```

where `rpihass` runs all services: `homeassistant`, `homeintent` (with `Rhasspy`), an `MQTT` server, ... 

So keep using the HI internal Rhasspy instance with an external MQTT broker (I'm already running Mosquitto in a separate docker container for other services) seems not to work - at least the internal Rhasspy instance wasn't configured with these values, it's still using the `Internal MQTT`. Can you confirm that? 

I would suggest to enable the option to use an external MQTT server even when `externally_managed` is set to `false`.
