### ISSUE TITLE
User-supplied slots for more custom-feeling intents

### ISSUE THREAD

**Issue by JarvyJ** [JarvyJ/HomeIntent#94]
So, after setting up an alias for tea timers:
```yaml
intents:
  set_timer:
    alias:
      - sentences: 
        - "Set a tea timer"
        slots:
          minutes: 5

      - sentences: 
        - "Set a coffee timer"
        slots:
          seconds: 90
```

I was thinking it might be kinda cool to setup an intent that uses user-supplied slots and values. It could look something like this:

```yaml
slots:
  custom_timer:
    add:
      - tea:
      slots:
        minutes: 5
      - coffee: 
      slots:
        seconds: 90
```

and then you could have a response like "setting a tea timer for 5 minutes". I guess overall it's a bit harder to understand than the alias for users to put in. Maybe having aliases use custom responses might be a better idea. There's definitely more things to think about here.
